#!/bin/bash

# =================================================================
#
# Work of the U.S. Department of the Navy, NIWC Pacific.
# Released as open source under the MIT License.  See LICENSE file.
#
# =================================================================

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly DIR

set -euo pipefail

if ! command -v pkl > /dev/null; then
  echo "pkl command is missing"
  exit 1
fi

function usage() {
  echo "Usage: ${0##*/} FORCE"
  exit 1
}

if [[ $# -gt 1 ]]; then
  usage
fi

force=${1:-0}

for package in ${DIR}/../packages/*; do
  if [ -d "${package}" ] && [ -f "${package}/PklProject" ]; then
      pushd "${package}" > /dev/null
      if [ ! -f "PklProject.deps.json" ]; then
        pkl project resolve
      elif [ "${force}" -eq 1 ]; then
        pkl project resolve
      fi
      popd > /dev/null
    fi
done