#!/bin/bash

# =================================================================
#
# Work of the U.S. Department of the Navy, NIWC Pacific.
# Released as open source under the MIT License.  See LICENSE file.
#
# =================================================================

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
readonly DIR

set -euo pipefail

if ! command -v pkl > /dev/null; then
  echo "pkl command is missing"
  exit 1
fi

function usage() {
  echo "Usage: ${0##*/}"
  exit 1
}

if [[ $# -ne 0 ]]; then
  usage
fi

for package in ${DIR}/../packages/*; do
  if [ -d "${package}" ] && [ -f "${package}/PklProject" ]; then
      pushd "${package}" > /dev/null
      pkl project package
      popd > /dev/null
    fi
done